.Dd October 26, 2020
.Dt SDN 1
.Os Linux
.Sh NAME
.Nm sdn
.Nd simple directory navigator
.Sh SYNOPSIS
.Nm sdn
.Op Ar line Ar point
.Sh DESCRIPTION
.Nm
is a simple directory navigator that you can invoke while editing shell
commands.  Use the
.Xr sdn-install 1
script to integrate it with your shell, then invoke it with M-o.
.Sh ENVIRONMENT
.Bl -tag -width 15n
.It Ev LS_COLORS
Used to retrieve filename colours.  The format is described in
.Xr dir_colors 5
and you can use the
.Xr dircolors 1
utility to initialize this variable.
.It Ev PAGER
The viewer program to be launched by the F3 key binding as well as to show
the internal help message.
.It Ev VISUAL , Ev EDITOR
The editor program to be launched by the F4 key binding.
.El
.Sh FILES
.Bl -tag -width 25n -compact
.It Pa ~/.config/sdn/config
Program configuration and state.
.It Pa ~/.config/sdn/bindings
Key binding overrides.
.It Pa ~/.config/sdn/look
Redefine terminal attributes for UI elements.
.El
